name: Version Bump

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump version and push tag
        run: |
          NEW_VERSION=$(npm version patch -m "release: %s")
          git push origin HEAD
          git push origin "$NEW_VERSION"
