permissions:
  contents: write

steps:
  - uses: actions/checkout@v4
    with: fetch-depth: 0

  - name: Bump version
    run: |
      git config user.name github-actions
      git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      npm version patch -m "release: v%s"

  - name: Push tag
    run: |
      TAG=$(git describe --tags --abbrev=0)
      git push origin "refs/tags/$TAG"
